# Generated by Django 6.0.2 on 2026-02-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NayxusStock', max_length=100, verbose_name='Nom du magasin')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Paramètres du magasin',
                'verbose_name_plural': 'Paramètres du magasin',
            },
        ),
    ]
